Add python-debianbts as a dependency in setup/README (Closes: #823118)
Needed to run the test suite:

    ======================================================================
    ERROR: test_importing_rm (test_imports.ImportTestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/srv/daksrc/tests/test_imports.py", line 15, in test_fn
        __import__('dak', fromlist=[cmd])
      File "/srv/daksrc/dak/rm.py", line 54, in <module>
        from daklib.rm import remove
      File "/srv/daksrc/dak/daklib/rm.py", line 52, in <module>
        import debianbts as bts
    ImportError: No module named debianbts

Signed-off-by: Luke Faraone <lfaraone@debian.org>