init_db.py: `Cnf.get' fix for `do_priority'
Apparently, the `get' method expects its secong argument to be an
string, not a number.  Without this fix I get

      p.level    = self.Cnf.get("Priority::%s", 0)
  TypeError: argument 2 must be string, not int

Setting the second arg as "0" makes the error disappear.

Signed-off-by: Mario Domenech Goulart <mario@ossystems.com.br>